export function renderReport(summary, graph) {
  const data = JSON.stringify({ summary, graph }).replaceAll('<', '\\u003c').replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');
  return `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'">
<title>Google Workspace · Read-only audit</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#0b1220;color:#e3eaf6;font:15px system-ui,sans-serif}header{padding:28px 32px 20px;border-bottom:1px solid #26364b}h1{margin:5px 0 10px;font-size:28px}h2{font-size:17px}p{color:#9cacc3;line-height:1.6}button,input,select{font:inherit;background:#142239;color:#e3eaf6;border:1px solid #42546e;border-radius:6px;padding:9px}button{cursor:pointer}button:hover{border-color:#66dfc2}label{display:inline-flex;gap:8px;align-items:center;margin:0 14px 10px 0}.tag{color:#66dfc2;font-size:12px;letter-spacing:1.5px}.stats{display:flex;gap:28px;flex-wrap:wrap}.stat strong{font-size:23px;display:block}.stat span{font-size:12px;color:#9cacc3}.layout{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:20px;padding:24px 32px}main{min-width:0}.panel{background:#111e31;border:1px solid #26364b;border-radius:12px;padding:18px;margin-bottom:20px}#canvas{width:100%;min-height:380px;background:#0b1627;border-radius:8px}svg text{fill:#dce8f8;font:12px system-ui}svg .node{cursor:pointer}svg .node:hover rect{stroke:#fff;stroke-width:2}#details{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.6 ui-monospace,monospace;max-height:580px;overflow:auto}#results{max-height:270px;overflow:auto;display:grid;gap:6px}#results button{text-align:left;font-size:13px}.muted{color:#9cacc3;font-size:13px}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:10px 8px;border-bottom:1px solid #26364b;text-align:left}.tablewrap{overflow:auto}#issues{max-height:240px;overflow:auto;overflow-wrap:anywhere}li{margin-bottom:10px;color:#b6c4d8}.legend{color:#9cacc3;font-size:12px}.notice{color:#efc77f} @media(max-width:950px){.layout{grid-template-columns:1fr;padding:16px}header{padding:20px}}
</style>
<header><div class="tag">READ-ONLY · GOOGLE WORKSPACE</div><h1>Cells, formulas & script links</h1><p id="status"></p><div class="stats" id="stats"></div></header>
<div class="layout"><main><section class="panel"><h2>Dependency map</h2><label>View <select id="view"><option value="overview">Sheets & functions</option><option value="detail">Cells & ranges</option></select></label><button id="reset">Reset selection</button><p class="legend">Arrow: input → formula · range → script read · script → possible write · caller → callee</p><p id="mapnote" class="muted"></p><svg id="canvas" role="img" aria-label="Dependency graph"></svg></section><section class="panel"><h2>Sheet coverage</h2><div class="tablewrap"><table><thead><tr><th>Sheet</th><th>Hidden</th><th>Populated</th><th>Formulas</th><th>Errors</th></tr></thead><tbody id="sheets"></tbody></table></div></section><section class="panel"><h2>Unresolved relationships & collection issues</h2><ul id="issues"></ul><p id="issuecount" class="muted"></p></section></main><aside><section class="panel"><h2>Find a cell or function</h2><input id="search" placeholder="Sheet, A1, function or formula" aria-label="Find a node" style="width:100%"><p class="muted">Click a result or map node to inspect its evidence and neighboring links.</p><div id="results"></div></section><section class="panel"><h2>Selected evidence</h2><div id="details">Select a node to inspect it.</div></section><section class="panel"><h2>What this report covers</h2><ul id="limits"></ul></section></aside></div>
<script id="audit-data" type="application/json">${data}</script><script>
const {summary:s,graph:g}=JSON.parse(document.getElementById('audit-data').textContent);
const $=id=>document.getElementById(id), make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e};
$('status').textContent=s.mode.toUpperCase()+' · '+s.status+' · '+s.coverage.coveredCells.toLocaleString()+'/'+s.coverage.expectedCells.toLocaleString()+' allocated cells covered in readable spreadsheets · '+s.coverage.spreadsheetsRead+'/'+s.coverage.spreadsheetsExpected+' spreadsheets · '+s.coverage.scriptsRead+'/'+s.coverage.scriptsExpected+' scripts';
if(s.status!=='complete')$('status').className='notice';
for(const [name,value] of [['Populated cells',s.populatedCells],['Formulas',s.formulas],['Functions',s.functions],['Links',s.edges],['Unresolved / issues',s.issueCount]]){const d=make('div');d.className='stat';d.append(make('strong',value.toLocaleString()),make('span',name));$('stats').append(d)}
for(const row of s.sheets){const tr=make('tr');for(const value of [row.bookTitle+' / '+row.title,row.hidden?'Yes':'No',row.populatedCells,row.formulas,row.errors])tr.append(make('td',value));$('sheets').append(tr)}
for(const issue of g.issues.slice(0,200))$('issues').append(make('li',JSON.stringify(issue)));
$('issuecount').textContent=g.issues.length>200?'Showing 200 of '+g.issues.length+' issues. All issues are in graph.json.':g.issues.length+' issues recorded.';
for(const line of s.limitations)$('limits').append(make('li',line));
const byId=new Map(g.nodes.map(n=>[n.id,n]));let selected=null;
function select(id){selected=id;const n=byId.get(id),links=g.edges.filter(e=>e.source===id||e.target===id);$('details').textContent=JSON.stringify({node:n,links:links.slice(0,100),linkCount:links.length},null,2);draw()}
function search(){const q=$('search').value.toLowerCase();$('results').replaceChildren();const found=g.nodes.filter(n=>(n.label+' '+(n.formula||'')).toLowerCase().includes(q));for(const n of found.slice(0,40)){const b=make('button',n.label);b.onclick=()=>{ $('view').value=n.kind==='sheet'?'overview':'detail';select(n.id)};$('results').append(b)}if(found.length>40)$('results').append(make('p','Showing 40 of '+found.length+' matches; narrow your search.'))}
const ns='http://www.w3.org/2000/svg';function svg(tag,attrs,text){const e=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function draw(){const overview=$('view').value==='overview';const project=id=>overview?(byId.get(id)?.parent||id):id;let all=overview?g.nodes.filter(n=>['sheet','function'].includes(n.kind)):g.nodes.filter(n=>n.kind!=='sheet');
let es=g.edges.map(e=>({...e,source:project(e.source),target:project(e.target)}));
if(selected){const focus=project(selected),related=new Set([focus]);for(const e of es)if(e.source===focus||e.target===focus){related.add(e.source);related.add(e.target)}all=all.filter(n=>related.has(n.id))}
const total=all.length;all=all.slice(0,45);const ids=new Set(all.map(n=>n.id));es=es.filter(e=>ids.has(e.source)&&ids.has(e.target));const unique=new Map();for(const e of es){const key=e.source+'|'+e.target+'|'+e.relation;if(unique.has(key))unique.get(key).count++;else unique.set(key,{...e,count:1})}es=[...unique.values()];const totalLinks=es.length;es=es.slice(0,160);
$('mapnote').textContent='Showing '+all.length+' of '+total+' matching nodes and '+es.length+' of '+totalLinks+' visible links. '+(selected?'Selection shows direct neighbors. ':'Search to focus larger graphs. ')+(overview?'Links are grouped by sheet/function.':'Ranges stay symbolic; use trace for range overlap.');
const canvas=$('canvas');canvas.replaceChildren();const width=850,cols=3,rows=Math.ceil(all.length/cols),height=Math.max(400,rows*110+60);canvas.setAttribute('viewBox','0 0 '+width+' '+height);const defs=svg('defs',{}),marker=svg('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:7,markerHeight:7,orient:'auto-start-reverse'});marker.append(svg('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#7a94b8'}));defs.append(marker);canvas.append(defs);
const pos=new Map(all.map((n,i)=>[n.id,{x:35+(i%cols)*280,y:35+Math.floor(i/cols)*110}]));for(const e of es){const a=pos.get(e.source),b=pos.get(e.target),color=e.relation==='script-write'?'#e8b567':e.relation==='script-read'?'#71cfb9':'#657fa4';let d;if(e.source===e.target)d='M '+(a.x+190)+' '+a.y+' C '+(a.x+240)+' '+(a.y-30)+' '+(a.x+100)+' '+(a.y-30)+' '+(a.x+130)+' '+a.y;else d='M '+(a.x+110)+' '+(a.y+54)+' C '+(a.x+110)+' '+(a.y+90)+' '+(b.x+110)+' '+(b.y-35)+' '+(b.x+110)+' '+b.y;const path=svg('path',{d,fill:'none',stroke:color,'stroke-width':1.5,'marker-end':'url(#arrow)',opacity:.7});path.append(svg('title',{},e.relation+' × '+e.count));canvas.append(path)}
for(const n of all){const p=pos.get(n.id),gr=svg('g',{class:'node',tabindex:0,role:'button','aria-label':n.label,transform:'translate('+p.x+' '+p.y+')'});gr.append(svg('rect',{width:230,height:54,rx:8,fill:n.kind==='function'?'#2e2448':'#173143',stroke:project(selected)===n.id?'#fff':'#426981'}),svg('text',{x:10,y:21},n.label.length>31?n.label.slice(0,29)+'…':n.label),svg('text',{x:10,y:41,opacity:.6},n.kind));gr.append(svg('title',{},n.label));gr.onclick=()=>select(n.id);gr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(n.id)}};canvas.append(gr)} }
$('search').oninput=search;$('view').onchange=()=>{selected=null;draw()};$('reset').onclick=()=>{selected=null;$('details').textContent='Select a node to inspect it.';draw()};search();draw();
</script></html>`;
}
